### ISSUE TITLE
NeuraSDK/NeuraSDK.h file not found - xcode build failure

### ISSUE THREAD

**Issue by tripleorange** [NeuraLabs/react_native_sample_app#2]
I'm continuing to bump up against issues with the sdk - is this a file structure issue? - do you have a working react native sample app currently

**Comment by youvalv** [comment]
Hi,

we are working on updating the react native plugin, but in the meantime, you can find the NeuraSDK.framework (where the neurasdk.h file is contained) here:
https://cdn.theneura.com/files/product/ios/sdk/NeuraStandaloneSDKPackage.zip

you can find it using the "Get the SDK" button on this page: https://dev.theneura.com/docs/guide/ios/setup
